services:
  - type: web
    name: servicedesk-backend
    env: node
    buildCommand: "npm install && cd apps/backend && npx prisma generate && npx nest build"
    startCommand: "cd apps/backend && npm run start:prod"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false